project:
  type: website
  output-dir : docs

website:
  description: "A blog built with Quarto"
  site-url: https://rlackdrhkd.github.io
  title: "Hslee's Archive"
  navbar:
    background: "#446E9B"
    foreground: "#ffffff"
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/rlackdrhkd
  page-footer:
    background: "#f5f5f5"
    center: "© 2026 Hslee's Archive · Built with [Quarto](https://quarto.org)"

format:
  html:
    theme: spacelab
    css: styles.css
    highlight-style: github
    code-copy: true
    toc: true
    toc-depth: 3
    smooth-scroll: true
