project:
  type: website
  output-dir : docs

website:
  description: "A blog built with Quarto"
  site-url: https://your-website-url.example.com # you must change this appropriately for RSS feeds to work properly
  title: "Hslee's Archive"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: bluesky
        href: https://bsky.app/
format:
  html:
    theme: spacelab        # ✅ spacelab 테마 적용
    highlight-style: github
    code-copy: true        # 코드 복사 버튼
    toc: true              # 목차 자동 생성
